sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product ittn-016
env:
  global:
    - secure: "rp+SO6D6K7ETYPX4Jk+TyfM2yJad2FyT5tAxLBD++2f2rg/uXkOYzMfYS/Y8+z2lVnpKZCFONnGQyx5O3yjIsGJ+/gt8Pvv2C42SbvTQkoflW+4G8ZjUankILoTYtE8Ncgt3b6veOJ1RQbluLhBXfjiH9pWs/+n2GXTKYOp+oo3bXMftwavHEf6bmPL38Mdpnj5WPtDkW0IzO400x7k5VlrjY2xnVltxzUjPQvFao/XKe+GG13IUSbvXQsI6XFcd26TduM7up7gBw2ZHCgo28AqetE3qZWTcp1hFHdp0RPC6e1j03A3OvDDj3+5NKVCIY2qbcv07d2pPUg6HN5Njbtl8//HoUuEipWjYkceJ/KXLfcAEXdqPQivpMnDKrNGQQbZDie/5lNrYxsii5AZZ35SPMEb3972pRc4nOmi5fRpNfsBRj6xAXkLcoFxhzHdxp3Xv8ftU5bcoy6y3FGbNgJjjIjBTqSGJ+J4OF6Oiuu84xBC5vN+8UxLSGh13KG0gwkMdm2b6vyMDjxDT/u5s5JxiKFR60i9y9LajRwk8iIv/4Kr/ZlWfD9kNnR78AgicLKgBKGhBvvcyq+G0GFlTJBgfvLWDbjyMoQCLJm64TlDQbOepfzJKzec6FuE6ZY/PZZRrCngT0/KtPWP9nPRxmj3asGqJuuQs1eXiBwN/8e0="
    - secure: "ea8fmFgkHhCmV/XcOsE9KRhe0INOOFsTLWsPnCSFtmriv6SzSlULC6hf3SgpXKhPz0cM7fiNds0T6ICame96+wH1M9CtXXu+2+Thn/FFTdSPR4HaWYFD1ImHFfTrxTBNGfZ0DlHg5BqXjkl7sV98tmjqHKMWtpv54RdSQt86zgVSCzgRv8CxRG528F0fw2dKmFHE3cCuoGS6aiIcMfWdzx+AthU02EjjMyglf8gOduMJDAHrG6+kgwxORO5XI7D56FyyHZvBxoKW39q89cyEti3PKmBdkz2EJl71CQ6IpmD5zDVwWDhJa/A/cq5QIKS/6m9Ubj7gW6T35pxi7puFu6BgajcyEOZwy1mFoeWrk0XEGuxFKxAHsPXc2hC/6Jqaw/ASBlz6Ppd5eyr4YuIjRmqfJ3bVTiWT6v7bcs/6N6OgEPehhCbFvKX9XoIMih043ITK5k0NVAQb10Bw2yG2i73Im7K/uj3UQTyDfBF4UXgOXgm/ADs3vFlkXu68WPIh8u4cEXVOJuXAnTmBRVkNDf/bOlFwMacEbiu2oO+pOhPULZLckIQKuFiN0rURqTpQGLWJ2D5Z0yyvDntih+cI/Cn+VlqSfAPaEjWYEIqscfWdRQmMlXqDgQdNfVGPb/20N2bpMyeX4AZ/JzPftJGpVVV+VPrSK9+8axXGZGR/Q7A="
